[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
descholarism = "81yXP67oLaVK2bo3KGwk6zNFZiuCn5uss1DWaM8vshm6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
